project:
  type: website
  output-dir: _site

website:
  title: "Artificial Intelligence Policy"
  site-url: https://jacklreilly.github.io/aip_s26/
  repo-url: https://github.com/jacklreilly/aip_s26
  navbar:
    title: "**Artificial Intelligence Policy**"
    right:
      - href: overview.qmd
        text: 🏠 Overview
      - href: schedule.qmd
        text: 📅 Schedule
      - href: content/index.qmd
        text: 📚 Content
      - href: work/index.qmd
        text: 📝 Work 
      - text: 🏫 Policies
        menu: 
        - text: 🏛️ Campus Policies
          href: policies.qmd
        - text: 🤖 AI & LLMs
          href: ai.qmd
      - text: "🔗 Links"
        menu:
        - text: 💻 Blackboard
          href: https://blackboard.syr.edu/
        - text: 💬 Discussion Board
          href: https://teams.microsoft.com/l/channel/19%3Ao9tovA_55UGMcoafRyUYhZus5Ju63bfSTr8SreWTZ241%40thread.tacv2/General?groupId=637c3533-290a-4524-9088-f07060f76735&tenantId=4278a402-1a9e-4eb9-8414-ffb55a5fcf1e

  page-footer:
    left: |
      © 2026 Jack Reilly<br>
      [Contact](mailto:jlreilly@syr.edu)
      
    center: |
      
      
    right: |
      Built with [Quarto](https://quarto.org)<br>
      [About](/about.qmd)

  sidebar:
    - id: content
      style: docked
      title: "Content"
      #logo: images/pai600_dwv_logo2.svg
      contents:
        - section: "1. Philosophy"
          href: content/index.qmd
          contents:
          - content/w11.qmd
          - content/w12.qmd
          - content/w21.qmd
          - content/w22.qmd
          - content/w31.qmd
          - content/w32.qmd                    
        - section: "2. Technology"
          href: content/index.qmd
          contents:
          - content/w41.qmd
          - content/w42.qmd
          - content/w51.qmd
          - content/w52.qmd
        - section: "3. Business"
          href: content/index.qmd
          contents:
          - content/w61.qmd
          - content/w62.qmd
          - content/w71.qmd
          - content/w72.qmd
        - section: "4. Geopolitics"
          href: content/index.qmd
          contents:
          - content/w81.qmd
          - content/w82.qmd
          - content/w91.qmd
          - content/w92.qmd

    - id: work
      style: docked
      title: "Work"
      #logo: images/pai600_dwv_logo2.svg
      contents:
        - section: "Debates"
          href: work/dguidelines.qmd
          contents:
          - work/dguidelines.qmd
          - work/dtips.qmd
          - work/d1res.qmd
          - work/d2res.qmd
          - work/d3res.qmd
          - work/d4res.qmd

        - section: "Assignments"
          href: work/index.qmd
          contents:
          - work/assign1.qmd
          - work/assign2.qmd

        - section: "Final Project"
          href: work/final.qmd
          contents:
          - work/final.qmd

        - section: "Exams"
          href: work/examguide.qmd
          contents:
          - work/examguide.qmd

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
execute:
  freeze: auto



