---
title: "Overview"
format: 
    html: default
    pdf: default
    docx: default
    rtf: default
---

## 🏛️ Course Information

### Class

**Time**: Tuesdays and Thursday, 2:00 PM - 3:20 PM

**Location**: Eggers 070

### Instructor

**Professor Jack Reilly**

**Office**: Eggers 225

**Office Hours**: Tuesday and Thursday, 11 AM - Noon, Wednesday 1:30-2:30 PM, and by appointment.[^oh]

[^oh]: In addition to formal office hours, I have an open door policy - feel free to stop by if you see the door open. In particular, I stay around after class for up to half an hour if students come by - feel free to stay after and meet with me. 

**Phone**: 315-443-2687 (office)

**e-mail**: <jlreilly@syr.edu>

### Quick Description
This course is designed for students who want to think critically about artificial intelligence and design artificial intelligence policies for government, business, and nonprofit organizations of all sizes.

### Course Description
This course serves as in introduction to the politics and policy of artificial intelligence.  It presumes no particular prior knowledge of artificial intelligence, political science, public policy, or computer science; rather, it will introduce students to what artificial intelligence is as well as to the ethics of AI, its social implications, and the policy choices around AI that currently face governments, corporations, and organizations worldwide. This is a "non-technical" course: assignments will include reading, class discussion and leadership, debates, writing, and learning about the use of AI tools and prompts to generate output. Students will not be expected, however, to program or write any formal code. 

### Course Structure
 
**Principle - Practice - Politics - Policy**

The course has four sequential units. First, we start with an introduction to the philosophy of artificial intelligence itself. What is "intelligence" and "consciousness" in the first place? What are minds? What are agents and legal persons, and when are agents responsible for their actions? What is artificial intelligence, and what is artificial "general" intelligence? Second, we proceed to discuss the mechanics of current computational approaches to AI, with a particular focus on large language models (such as OpenAI's ChatGPT), including approachable, non-technical overviews of the principles behind machine learning, neural networks, and assorted technologies that have given rise to the current state of the art in AI.  Third, we consider the societal impacts of current artificial intelligence systems, including data practices as well as current AI applications, uses, risks, and ethics. Fourth, we turn to policy, examining the decisions in front of governments, companies, and organizations in the United States and worldwide as well as complications in the policy process for producing effective AI legislation.

### Prerequisites

Introductory coursework in (any) related area(s). No particular knowledge is expected, but the reading level is high and this course may not be suitable for first year students.

While this course has no *formal* pre-requisites, it does have a substantial *informal* prerequisite: **motivation**. This class is conducted as a seminar, not a lecture, and interest and participation is presumed and required.

### Learning Objectives

1. Explain the core technical, economic, and political forces that shape how modern AI models are developed, deployed, and governed.
2. Critically evaluate and debate alternate perspectives on contemporary AI policy issues, using evidence to construct and defend reasoned arguments.
3. Design and evaluate AI policy proposals by applying principles of data ethics, policy analysis, and policy design to real-world issue domains.

## 📘 Materials

### Books

- **Required**
    - None. All materials will be available online. 
    - Materials may require logging in through the library for access.
- **Recommended** 
    - Haugeland et al, 2023. Mind Design III: Philosophy, Psychology, and Artificial Intelligence.

### Computing
We will use of AI models in class as end-users, so you should have a computer you can use to access them.  No coding will be required in the course. 

Syracuse University has a campus-wide license to the enterprise version of Anthropic's Claude, which gives you increased usage before being your compute is limited. Anthropic also guarantees Syracuse that it will not train Claude's models on your data. I recommend you use it when asked in course assignments if you do not have higher-level access to another LLM. [Syracuse University: Claude Enterprise](https://its.syr.edu/claude/)


### Online Course Resources

#### Website
[This course website](overview.qmd) is our primary source of course organization and material: here, you can find the course syllabus, daily content, assignments, and more.

#### Blackboard
Blackboard is our internet-based course platform:  <http://blackboard.syr.edu>. In it, you will find submission portals for assignments and a link to our course webpage, along with (potentially) a few resources that are copyright protected and not suitable to post here.

#### Microsoft Teams
In addition to Blackboard, we'll have a class discussion channel in Microsoft Teams for discussion question sharing as well as for sharing news articles.  Make sure you set up easy access for yourself wherever is convenient.

## 📌  Course Requirements

### Overview

1.  **Seminar Participation** (20%)
    - Attendance, Reading, and Participation
	- Discussion Questions
	- AI News Submissions
	- Discussion Leadership
2. **Prepared Work for Class** (40%)
    - Debates (30%)
	- Short Assignments (10%)
3. **Core Exam** (20%)
4. **Final Project** (20%)
	- Presentation
	- Paper

### Seminar Participation

#### Daily Attendance, Participation, and Reading
 This is a preceptorial-style seminar taught at a high level: it only works if everyone takes part. I have a high opinion of your intellectual capability and a similarly high opinion of the quality of your potential contributions - make sure to show them to me! 

#### Discussion Questions
 Submit discussion questions or points (broadly construed) to the class by 9 AM on the day of class. Make sure to send messages to the course Teams chat so everyone can read them. 

#### AI News Submissions
 In class, we'll time in class to discuss AI news from the week. (Especially if something particularly interesting happens . . . which, because this is AI, happens a lot).  If you come across interesting AI news - or broad tech industry news - submit it to our Teams chat.

#### Discussion Leadership
 Each class has an assigned discussion leader from among the students.  While all students are under an obligation to read (or listen, or watch) the material each day from class, the discussion leader has a special role as the person to starts our discussion for the day rolling, and steps in should our discussion of the day's material falter.

#### Participation Grading Policy
 A seminar like this doesn't work if everyone only seeks to do the bare minimum. Informed class participation is expected and required each day in class; you shouldn't be counting things like *"I submitted a number of news articles already this semester, so I no longer need to submit news articles or talk in class".*  Participate across all elements of the seminar as and when the spirit moves you, and keep that participation up through the semester, and you'll do fine for this portion of the class.[^partic]
 
 [^partic]: For the grade for this section, I hope and expect to be able to simply award full points to everyone based on apparent enthusiasm and contributions across the whole semester.}

With that said, it is useful to have some baselines and expectations for everyone to keep in mind. A few that are useful:

- *Attendance:* One of the guiding principles of my class is that you are adults, and thus, capable of managing your own obligations and time. I have little interest in policing your lives, and I understand that everyone has bad days, things that come up, etc.[^att] You can miss up to three days of class without excuse or penalty, unless that day is a day you have a special obligation.  If you are supposed to be a discussion leader, or giving a presentation, taking part in a debate, or miss more than three days, make sure to send me a note.  
- *Discussion Questions:* At least one each day. (Although do note: you should sometimes submit more than one, too!)
- *In-Class Participation:* We should hear your contributions every day. We'll have systems in class to make sure that everyone gets a turn.  I won't be keeping exact tallies of who said what, or how much, but I will take note of your general contribution tendencies.  
- *News Submissions:* At least two news submissions per semester (hopefully more)!
- *Discussion Leadership:* Split evenly according to the number of students in the class.
\end{itemize}  

[^att]: I also understand that some of these things that come up may be things you don't want to discuss with your professor.  That's OK!  The attendance policy is designed so that you typically don't have to tell me you missed because you have a medical emergency or a family matter you'd rather not discuss.

### Prepared Class Work
 
#### Debates
We will have six formal debates in the class, following a modified Lincoln-Douglas debate format (if you are unfamiliar with these rules, don't worry! We'll cover them.)  Each student will have a role in each debate, although not all roles are equal: it is easier to *judge* than it is to *affirm* or *negate*.  All students will have equal debate responsibilities across the class. 

#### Short Assignments
Small assignments about AI tools will be given throughout the semester.  They may involve presentations to the class.

### Core Exam
An in class test on AI basics, held in the middle of the semester.

### Final Project
A final research project on an aspect of AI policy. (There will be options.) Graduate students will have higher expectations than undergraduates.

## 🎓 Course Expectations & Guidelines 

### Etiquette & Decorum

This is a upper level undergraduate and graduate course:  I take it for granted that you have a basic interest in the material and an enthusiastic attitude toward participation. A university classroom is fundamentally a learning community that operates on respect: be courteous to fellow students and the professor, attend class on time, listen to fellow seminar participants when they talk, and disagree (or agree) with others’ arguments professionally. Keep cell phones and other technology silenced and out of sight unless doing something directly relevant to the discussion in the class.[^cell]

[^cell]: Remember that technology present a significant negative externality: it is not just you that is distracted, but it is you who are distracting others as well with the bright shiny colors on your screen.

### Office & Consultation Hours, Appointments

I encourage you to chat with me at any point if you have questions about the course. You are always welcome to drop by my office hours, and can schedule a meeting with me by going to my website here: [http://jacklreilly.github.io](http://jacklreilly.github.io). You do not need an appointment for regularly scheduled drop-in office hours: they are there for you! Furthermore, I have a general open-door policy: feel free to stop by to see if my door is open, and if it is, just come on in.  (Don't feel like you're intruding! I'll tell you if it's not a good time.)

### E-mail

Email is the best way to contact me. I try to be pretty responsive, but as a baseline, I always aim to get back to you in a modified 24-hour fashion: by the end of the business day the day after you email (at minimum). So if you email me at 2 PM Tuesday, I'll get back to you by 6 PM Wednesday at the latest; if 10 PM Thursday, by 6 PM Friday; if you email me at 3 PM on Friday, by 6 PM Monday, etc.[^1]  

::: {.callout-note}
If your email requires a long response, expect me to encourage you to meet with me in person so we can have a more effective discussion.  
:::

[^1]: Usually I aim to be much much faster! But if you don't hear from me by this baseline, feel free to bump a reminder.  No hard feelings.  Sometimes things get busy and I lose track of an email.


### Artificial Intelligence and Class Technology Policy
 To be discussed (and decided upon!) in class on a per-assignment basis.

## 📊 Learning Objective Assessment

### Course Assessment Plan
| **Learning Objective** | **Assessment Measure** |
|------------------------|------------------------|
| Explain the core technical, economic, and political forces that shape how modern AI models are developed, deployed, and governed. | Core Exam |
| Critically evaluate and debate diverse perspectives on contemporary AI policy issues, using evidence to construct and defend reasoned arguments. | Debates |
| Design and evaluate AI policy proposals by applying principles of data ethics, policy analysis, and policy design to real-world issue domains. | Final Project |
