---
title: "12.2.2 - The Singularity and The Future"
---

#### 🧠 Think: 
- *What does the future hold?  Is there an AI Singularity on the horizon?*
- *Are current AI paradigms, products, and tools sufficient to bring about substantial technological and societal change? Do we need a new paradigm for AI to continue to advance? Is there another AI winter on the horizon without substantial new scientific and technological invention?*
- *Is AI a greater or lesser exisential risk than other threats (nuclear, climate, disease, etc) facing humanity?  Or is AI not really about threat at all, and more about promise? Can we build a better future for us all with technology?*

#### 📖 Read: 
- Blili-Hamelin et al, 2025. "[Stop Treating AGI as the North Star of AI research](https://arxiv.org/pdf/2502.03689)"

#### 📺 Watch: 
- Mitchell, 2025. "[The Past, Present, and Uncertain Future of AI](https://www.youtube.com/watch?v=xdTOrk9jOp0)"

#### 🎧 Listen: 
- *Optional: *Complexity* podcast, Season 2, Episode 6: "[AI's Changing Seasons](https://www.santafe.edu/culture/podcasts/episode-6-ais-changing-seasons)"

#### 🌐 Browse:
*new FB guy venture
   - Wait But Why (Urban), 2015. "The AI Revolution: The Road to Superintelligence"
     - [Part 1](https://waitbutwhy.com/2015/01/artificial-intelligence-revolution-1.html)
     - [Part 2](https://waitbutwhy.com/2015/01/artificial-intelligence-revolution-2.html)
   - "[AI 2027](https://ai-2027.com/)"
    - *See also*: [The AI 2027 scenario and what it means: a video tour](https://80000hours.org/2025/07/the-ai-2027-scenario-and-what-it-means-a-video-tour/) 

#### 📚 Additional Resources:
  - Kurzweil, *The Singularity is Near* and *The Singularity is Nearer*
  - Altman, 2025. "[The Gentle Singularity](https://blog.samaltman.com/the-gentle-singularity)"
  - Shojaee, 2025. "The Illusion of Thinking: Undestanding the Strengths and Limitations of Reasoning Models via the Lens of Problem Complexity(https://machinelearning.apple.com/research/illusion-of-thinking)" Apple.
    - *See also*: Marcus, 2025. "[Seven replies to the viral Apple reasoning paper – and why they fall short](https://garymarcus.substack.com/p/seven-replies-to-the-viral-apple)"

#### 📝 Submit:
  - Discussion question to course chat

::: {.callout-tip}
### Tip
 - "📖 Read", "🎧 Listen", and/or "📺 Watch" items are required content for the day, and should be read/heard/watched before class on that day.
 - "🌐 Browse" items should be briefly looked at but do not need to be read deeply unless you want to
 - "📚 Additional Resources" do not need to be looked at; they are there to serve, if useful, as further references for your debates, final projects, and general edification later.
:::