---
title: "2.1 - CC: Emergence"
---

#### 🧠 Think 

- *Is "intelligence" an emergent phenomenon? Or something different? What does it mean to be "intelligent"? What about consciousness? When do we start treating a system as more than the sum of its parts, and why?*

#### 📖 Read
- Goldstein, [Emergence as a Construct: History and Issues](http://mainline.brynmawr.edu/Courses/cs361/spring2008/Readings/Construct.pdf)
   - *Alternate*: Krakauer, et al. 2025. "[Large Language Models and Emergence: A Complex Systems Perspective](https://arxiv.org/abs/2506.11135)"

#### 🌐 Browse

- Krakauer, "[What is Complexity?](https://www.youtube.com/watch?v=JR93X7xK05o)" *Santa Fe Institute Lecture*. 
- Schultz, "[Flocking together: Study shows how animal groups find their way](https://www.princeton.edu/news/2005/02/03/flocking-together-study-shows-how-animal-groups-find-their-way)"
- Roose, ["A Conversation With Bing's Chatbot Left Me Deeply Unsettled"](https://www.nytimes.com/2023/02/16/technology/bing-chatbot-microsoft-chatgpt.html) NYTimes.

#### 📚 Additional Resources
- Boden, "Autonomy and Artificiality" from *The Philosophy of Artificial Life*
- Bedau, Mark. "Weak Emergence"
- Johnson, "Eliminating the mystery from the concept of emergence"
- Hofstadter, "Gödel, Escher, Bach: an Eternal Golden Braid"
- Langton, "[Computation at the Edge of Chaos](https://www.sciencedirect.com/science/article/abs/pii/016727899090064V)".  Physica D: Nonlinear Phenomena.
- Holland, John. *Emergence*
- Wolfram, *A New Kind of Science*
- Simon, Herb. *Sciences of the Artificial*
- "Emergent Properties", *Stanford Encyclopedia of Philosophy*

#### 📝 Submit
   - Discussion question to course chat

::: {.callout-tip}
### Tip
 - "📖 Read", "🎧 Listen", and/or "📺 Watch" items are required content for the day, and should be read/heard/watched before class on that day.
 - "🌐 Browse" items should be briefly looked at but do not need to be read deeply.
 - "📚 Additional Resources" do not need to be looked at; they are there to serve, if useful, as further references for your debates, final projects, and general edification later.

:::