---
title: "4.2 - Data Privacy and Algorithmic Bias"
---

#### 🧠 Think: 
- *How does the reliance on data in AI structure the way we think of AI's potential and power? When we think of the assorted challenges, from the technical to the social to the legal and back again, including training set issues, algorithmic bias, long tail problems, copyright issues, how do the makers of AI respond? How should the AI industry respond?*

#### 📖 Read: 
- Bender et al, 2021. "[On the Dangers of Stochastic Parrots: Can Language Models Be Too Big?](https://dl.acm.org/doi/10.1145/3442188.3445922)" *Proceedings of the 2021 ACM Conference on Fairness, Accountability, and Transparency*
- "[How Tech Giants Cut Corners to Harvest Data for A.I.](https://www.nytimes.com/2024/04/06/technology/tech-giants-harvest-data-artificial-intelligence.html)" NYTimes.

#### 🌐 Browse:
  - Hao, 2020. "[We read the paper that forced Timnit Gebru out of Google. Here’s what it says.](https://www.technologyreview.com/2020/12/04/1013294/google-ai-ethics-research-paper-forced-out-timnit-gebru/)" MIT Technology Review.
  - "[Oh Dear, Did Someone Steal Something from OpenAI?](https://www.wsj.com/tech/ai/oh-dear-did-someone-steal-something-from-openai-8e8a267c)" Wall Street Journal.
  - "[Meta torrented over 80 TB of Pirated Books to Train AI, Authors Say](https://arstechnica.com/tech-policy/2025/02/meta-torrented-over-81-7tb-of-pirated-books-to-train-ai-authors-say/)".  Ars Technica.
  - "[OpenAI Says DeepSeek May Have Improperly Harvested Its Data](https://www.nytimes.com/2025/01/29/technology/openai-deepseek-data-harvest.html)" NYTimes.
  - "[Thomson Reuters wins AI copyright 'fair use' ruling against one-time competitor](https://www.reuters.com/legal/thomson-reuters-wins-ai-copyright-fair-use-ruling-against-one-time-competitor-2025-02-11/)" Reuters.
  - "[Federal Court Rules Work Generated by Artificial Intelligence Alone Is Not Eligible for Copyright Protection](https://www.klgates.com/Federal-Court-Rules-Work-Generated-by-Artificial-Intelligence-Alone-Is-Not-Eligible-for-Copyright-Protection-8-30-2023)" Press Release.

#### 📚 Additional Resources:
- Sambasivan et al. 2021. "[“Everyone wants to do the model work, not the data work”: Data Cascades in High-Stakes AI](https://dl.acm.org/doi/10.1145/3411764.3445518)" *Proceedings of the 2021 CHI Conference on Human Factors in Computing Systems*
- D'Amour et al. 2022. "[Underspecification Presents Challenges for Credibility in
Modern Machine Learning](https://www.jmlr.org/papers/volume23/20-1335/20-1335.pdf)" *Journal of Machine Learning Research*
- Himmelreich, "[The Intersectionality Problem for Algorithmic Fairness](https://arxiv.org/abs/2411.02569)" Preprint.


#### 📝 Submit:
  - Discussion question to course chat

::: {.callout-tip}
### Tip
 - "📖 Read", "🎧 Listen", and/or "📺 Watch" items are required content for the day, and should be read/heard/watched before class on that day.
 - "🌐 Browse" items should be briefly looked at but do not need to be read deeply unless you want to
 - "📚 Additional Resources" do not need to be looked at; they are there to serve, if useful, as further references for your debates, final projects, and general edification later.
:::

