---
title: "8.2 - CC: AI Geopolitics"
---


#### 🧠 Think 
- *How do the technology demands of AI influence the behavior and relationship of governments and states worldwide? How does the need for advanced silicon fabs and manufacturing, in particular, structure geopolitical relations?*

#### 📖 Read 
- A *Stratechery* triad of articles:
  - "[A Chance to Build](https://stratechery.com/2024/a-chance-to-build/)" 2024.
  - "[AI Promise and Chip Precariousness](https://stratechery.com/2025/ai-promise-and-chip-precariousness/)" 2025.
  - "[TSMC Risk](https://stratechery.com/2026/tsmc-risk/)" 2026.

#### 📺 Watch 
- McGee, Patrick, "[Apple in China: The Capture of the World's Greatest Company](https://www.youtube.com/watch?v=NAj9zB4vaZc)", 2025. A *Daily Show* Interview with Jon Stewart.

#### 🌐 Browse
  - "[The CHIPS Act: How U.S. Microchip Factories Could Reshape the Economy](https://www.cfr.org/in-brief/chips-act-how-us-microchip-factories-could-reshape-economy)" *The Council on Foreign Relations*.
  - "[Micron signs historic deal with feds for $6.1 billion to build chip plants in Central NY](https://www.syracuse.com/business/2024/12/micron-signs-historic-deal-with-feds-for-61-billion-to-build-chip-plants-in-central-ny-idaho.html)" *Syracuse.com*
  - *The Economist*, "[America takes on China with a giant microchips bill](https://www.economist.com/united-states/2022/07/29/america-takes-on-china-with-a-giant-microchips-bill)"
  - *The Economist*, "[The gap between global threats and American power will grow in 2025](https://www.economist.com/the-world-ahead/2024/11/18/the-gap-between-global-threats-and-american-power-will-grow-in-2025)"


#### 📚 Additional Resources
  - Miller, 2023. *Chip War: The Fight for the World's Most Critical Technology*. Simon & Schuster.
  - McGee, 2025.  *Apple in China: The Capture of the World's Greatest Company*. Scribner.
  - *The Economist* "[New fronts will open up in the chip wars in 2025](https://www.economist.com/the-world-ahead/2024/11/20/new-fronts-will-open-up-in-the-chip-wars-in-2025)"
  - *Video:* [Lessons from Intel's First Foundry](https://www.youtube.com/watch?v=-Y9LWYmVQu0&t=5s)
  - Stratechery: "[Intel's Death and Potential Revival](https://stratechery.com/2024/intels-death-and-potential-revival/)"
  - *References on geopolitics, broadly:*
    - Nye, "[Soft Power](https://www.jstor.org/stable/1148580)"
    - "[Foreign Aid as Foreign Policy Tool](https://doi.org/10.1093/acrefore/9780190228637.013.332)"
    - Belt and Road: [Beijing Spins a Web of Chinese Infrastructure](https://www.wsj.com/articles/beijing-spins-a-web-of-chinese-infrastructure-1484560801) and [China Reboots Belt and Road](https://www.wsj.com/world/china/china-reboots-its-belt-and-road-initiative-99784632)
    - China in Latin America: <https://www.cfr.org/backgrounder/china-influence-latin-america-argentina-brazil-venezuela-security-energy-bri>
    - Current Taiwan-related events: <https://www.economist.com/leaders/2025/02/13/countering-chinas-diplomatic-coup>, <https://www.economist.com/international/2025/02/09/chinas-stunning-new-campaign-to-turn-the-world-against-taiwan>
    - American Military Power: <https://www.economist.com/briefing/2025/02/13/americas-military-supremacy-is-in-jeopardy>

::: {.callout-tip}
### Tip
 - "📖 Read", "🎧 Listen", and/or "📺 Watch" items are required content for the day, and should be read/heard/watched before class on that day.
 - "🌐 Browse" items should be briefly looked at but do not need to be read deeply unless you want to
 - "📚 Additional Resources" do not need to be looked at; they are there to serve, if useful, as further references for your debates, final projects, and general edification later.
:::