---
title: "9.1 - Foreign Policy"
---

#### 🧭 Reorienting and Taking Stock
- We are halfway through the class! 
- Today, we'll talk about geopolitics and foreign policy, but also recenter ourselves after the first half of the course (and after the week off).
- Where have we been, and what have we learned?  
- As we make our transition from talking about the philosophy, technology, and development of AI to talking about implications and impacts, what has been surprising?  
- Where do we *most* need policy, and what areas of AI most call out for intervention or support?

#### 🧠 Think 
- *What is AI's role in national defense and security?*
- *What responsibility do AI firms have to their "home" countries? Are they like defense contractors? Should the government have a special role in controlling AI technology and approving AI military technology sales?*

#### 📖 Read 
- Horowitz et al, "[AI, the International Balance of Power, and National Security Strategy](https://academic.oup.com/edited-volume/41989/chapter-abstract/386782541)". *The Oxford Handbook of AI Governance*
  - [Syracuse library link](https://doi-org.libezproxy2.syr.edu/10.1093/oxfordhb/9780197579329.013.55)
- Make sure to be familiar with the Anthropic/Department of Defense story for class discussion (see possible sources below).

#### 🎧 Listen: 
- Nothing required, but see the two (optional) recommended podcasts on Anthropic and the Pentagon under "🌐 Browse"

#### 🌐 Browse:
  - The recent Anthropic/Pentagon dustup is relevant and interesting from a variety of dimensions.
      - The core story:
        - "[Anthropic Refuses Pentagon’s Proposal to Loosen AI Guardrails](https://www.wsj.com/politics/national-security/anthropic-claude-defense-department-update-b17544d9). Wall Street Journal.
        - [OpenAI announces Pentagon deal after Trump bans Anthropic](https://www.npr.org/2026/02/27/nx-s1-5729118/trump-anthropic-pentagon-openai-ai-weapons-ban). NPR.
        - [Pentagon Officially Notifies Anthropic It Is a ‘Supply Chain Risk’](https://www.nytimes.com/2026/03/05/technology/anthropic-supply-chain-risk-defense-department.html). New York Times.
        - [A ‘Fight About Vibes’ Drove the Pentagon’s Breakup with Anthropic](https://www.wsj.com/tech/ai/anthropic-amodei-hegseth-ai-c12ee0df). Wall Street Journal.
        - [Anthropic Sues U.S. Defense Department, Pete Hegseth for Targeting the Company](https://www.wsj.com/politics/national-security/anthropic-sues-trump-administration-for-targeting-it-917b52ca). Wall Street Journal.
        - [A Guide to the Pentagon’s Dance With Anthropic and OpenAI](https://www.nytimes.com/2026/03/07/technology/anthropic-openai-pentagon-dario-amodei-sam-altman.html). New York Times.
      - A counter take: [Anthropic and Alignment](https://stratechery.com/2026/anthropic-and-alignment/), 2026. Stratechery blog.
      - Side effects: 
        - [The Pentagon-Anthropic Spat Is Good for China](https://www.wsj.com/opinion/the-pentagon-anthropic-spat-is-good-for-china-c7cf8fb2) Wall Street Journal.
        - [Anthropic’s Standoff With the Pentagon Shakes Up AI Talent Race](https://www.wsj.com/tech/ai/anthropic-trump-ai-talent-race-779c91d7) Wall Street Journal.
        - [OpenAI and Google employees rush to Anthropic’s defense in DOD lawsuit](https://techcrunch.com/2026/03/09/openai-and-google-employees-rush-to-anthropics-defense-in-dod-lawsuit/). Tech Crunch.
        - "[Anthropic’s AI tool Claude central to U.S. campaign in Iran, amid a bitter feud](https://www.washingtonpost.com/technology/2026/03/04/anthropic-ai-iran-campaign/)" Washington Post.
      - Two podcasts:
        - Dean Ball, 2026. "[Why the Pentagon Wants to Destroy Anthropic](https://www.nytimes.com/2026/03/06/opinion/ezra-klein-podcast-dean-ball.html)", *The Ezra Klein Show*, New York Times. Also see [Youtube link](https://www.youtube.com/watch?v=xc97F2CFBOY)
        - Mike Masnick, 2026. "[Anthropic doesn’t trust the Pentagon, and neither should you](https://www.theverge.com/podcast/893370/anthropic-pentagon-ai-mass-surveillance-nsa-privacy-spying)", *Decoder* with Nilay Patel, The Verge.  Also see [Youtube video link](https://www.youtube.com/watch?v=LLwVtA2K6eg)
  - "[What Google's Return to Defense AI Means](https://www.defenseone.com/business/2025/02/what-googles-return-defense-ai-means/402816/)". Defense One.
  - "[Elon Musk Moves Against the Russians in Ukraine](https://www.theatlantic.com/national-security/2026/02/elon-musk-ukraine-russia-starlink/686155/)".  The Atlantic.

::: {.callout-tip}
### Tip
 - "📖 Read", "🎧 Listen", and/or "📺 Watch" items are required content for the day, and should be read/heard/watched before class on that day.
 - "🌐 Browse" items should be briefly looked at but do not need to be read deeply unless you want to
 - "📚 Additional Resources" do not need to be looked at; they are there to serve, if useful, as further references for your debates, final projects, and general edification later.
:::