---
title: "Assignment 2 - Final Project Identification"
format: 
    html: default
    pdf: default
---

## Instructions

Submit a short (<1 page) abstract for your final project.  This abstract should include:

1. The topic you are choosing.  This includes both:
    - An identification of topic 1, 2, 3, or 4 from the [final project](final.qmd) page.
    - What subject within that topic you are choosing to work on for your project.
    
    Subjects within topics can be refined a little between identification and final project - I'm not looking for a final definitive exact topic identification for this assignment; I'm just looking for the overall field or subject you're focused on along with a little context.
2. Four citations for sources (from outside of class) that will begin informing your project.
3. Who you are working on your project with (if anyone). 

I strongly recommend meeting with me before submitting your project to talk it through.

## Submission

Each member of a group must submit their work independently (even though the content and files will be the same).

## Deadline

This assignment is due **March 26** (Week 10.2) to Blackboard as a PDF.