---
title: "Debate 1"
---


## Resolution

**An entity that passes the Turing Test is intelligent.**

## Amendments and Adjustments

- See [debate guidelines](d1guidelines.qmd) and [debate tips](dtips.qmd) for guidance and details.
- There are **no** adjustments to the standard debate format for this debate.

## Judge's Notes

It may help to think of this debate as a warm-up and illustration of the debate format. Later debates typically take place over more substantive policy disputes, with a potential greater role for evidence; this first debate is meant to illustrate the form of debate itself. It can help, for instance, to think about how you might have a debate over similar "debate training" resolutions, like:

- "A hot dog is a sandwich"
- "Cereal is a soup"
- "Peppers are fruits"
- "Pluto should be classified as a planet"
- "Chess is a sport"
- "Coffee is better than tea"
- "Breakfast food is superior to dinner food" 

You should expect that much of this debate will turn on how key terms like "intelligence" and "passing the Turing Test" are defined. It's not that there is no role for evidence in these resolutions - there is - but evidentiary proof is secondary to argumentative structure and strategy in winning these kinds of "training" debates.  Remember, the goal is not to be correct: the goal is to make the best case possible under reasonable definitions (and learn something substantive about both sides of a debate along the way).