---
title: "Debate 4 - Geopolitics"
---


## Resolution

**The United States government should further subsidize Intel's foundry operations.**

: Teams

| Affirm | Negate | Jury |
|:------|:------|:------------------------------|
| Team 2 | Team 1 | Team 3 |


## Amendments and Adjustments

- See [debate guidelines](dguidelines.qmd) and [debate tips](dtips.qmd) for guidance and details.
- The standard class debate format for this debate has been modified in the following ways:
    1. **Constructive** (4 min per team)
        - *1 min prep*
    2. **Cross-Examination** (8 min total, back and forth)
		- *2 min prep*
    3. **Rebuttal** (2.5 min per team)
		- *1 min prep*
    4. **Final Focus** (1 min per team)

## Judge's Notes

- This debate may require additional external research. Some potentially useful tidbits and starting points:
  - "[Intel's foundry future depends on securing a customer for next-gen chipmaking tech](https://www.reuters.com/world/asia-pacific/intels-foundry-future-depends-securing-customer-next-gen-chipmaking-tech-2025-07-25/)" Reuters.
  - "[Intel’s Big Bet: Inside the Chipmaker’s Make-or-Break Factory](https://www.nytimes.com/2025/10/09/technology/intel-chip-factory-fab52.html)" NYTimes.