---
title: "Debate 1"
subtitle: "Title"
---


## Overview

- A structured debate is a deliberation around a **resolution**.  
- There are two sides: 
    - One side that **affirms** (supports) the resolution, 
    - and another that **negates** (opposes) the resolution.  
- Each side offers facts, evidence, and argumentation in favor of their side.
- Our class debates are team-based modified Lincoln-Douglas[^ld] debates. They have four components:
    1. **Constructive** (3 min per team)
        - *1 min prep*
    2. **Cross-Examination** (5 min total, back and forth)
		- *1 min prep*
    3. **Rebuttal** (2 min per team)
		- *1 min prep*
    4. **Final Focus** (1 min per team)
- The debate round is organized and timed so that each team has an equal opportunity to present their case, respond to their opponents, and ultimately convince the jury to vote for them. 
- Your primary evaluation will be on the debate itself. You must submit citations for any non-class sources you reference in the debate, and the opposition may challenge you to support any fact that you use with a reference. If you cannot support the fact with a reference, the jury is instructed to disregard the point.
- Different team members should take “lead” presenting roles in the different debate components.  Teams are encouraged, although not required, to vary who takes “lead” in each component across different debates as well.
- Debate winners will be evaluated by the jury. 
- The jury must attempt to be as even handed and open-minded as possible: do not judge based upon which side you began thinking was the “correct” answer; judge based upon which side you think debated more effectively and persuaded toward their side. 

[^ld]: I tell you this intentionally so that you can, if you wish, go look up strategy for Lincoln-Douglas debate styles.  The modifications made are inspired partially by Public Forum debates and partially to allow for team-based debate.


## Structure and Flow

Each debate round has a specific structure.

1. The affirm side (team one) always goes first; the negate side (team two) always goes second.

**Part I: Constructive**

2. Team one presents their case. They don’t mention or directly talk about their opponents or their opponent’s case. The constructive is delivered by a single member of the team. Three minutes.

3. Team two presents their case. They don’t mention or directly talk about their opponents or their opponent’s case. The constructive is delivered by a single member of the team. Three minutes.

5. One minute of prep time.

**Part II: Cross Examination**

4. Team one and team two exchange asking questions. Team one asks first; team two, second.  Once team one finishes their question, team two responds.  Team two then immediately asks their question, followed by team one’s response and question, leading to team two’s response and question, and so on and so forth until time expires.

5. Three minutes of prep time.

**Part III: Rebuttal**

6. Team one has an opportunity to rebut the arguments presented by their opponents in the debate. Two minutes.

7. Team two has an opportunity to rebut the arguments presented by their opponents in the debate. Two minutes.

7. One minute of prep time. 

**Part IV: Final Focus**

10. Team one summarizes why they think the judges should vote for them. One minute.

11. Team two summarizes why they think the judges should vote for them. One minute.

## Team Roles

There are at least five roles, per team, per debate:

1. Constructive
2. Cross-Examination: Questioner
2. Cross-Examination: Responder
4. Cross-Examination: Note-taker
5. Rebuttal 
6. Final Focus

Not all roles are necessarily equal. Delivering the constructive, for instance, is a three minute delivered speech, and the single most important part of the debate - but is also the only portion that can be fully and completely prepared ahead of time and does not need to respond in any way to what happens in real time.

Each student should take one or more roles, as necessary, but it is the entire team's responsibility to coordinate and prepare each section.

## General Tips and Advice 

1. Refer to the other team as “our opponents” or “my opponent”.
2. Think carefully about the resolution. What *exactly* is the resolution asking you to debate? Do not allow yourself to be distracted by anything off topic (which good debaters will try to do, of course). 
    - The only thing you need to do to beat an genuinely off topic argument is say “Judge, please disregard my opponent’s contention because it is off topic.” (Of course, if the jury does not think that a contention is off topic, this may backfire.)
3. Define the terms of the debate. Resolutions, by their nature, have inherent ambiguities.  Define and frame the resolution further in a way that is simultaneously fair and that gives you an argumentative advantage. Make the terms of the debate clear to the judges: what, for instance, should determine a winner and loser in the debate?  What points does your side need to make and what points does the other side need to make to win?

4. In oral debate presentation, clarity is key. **Subtlety is not your friend.** Use the following format for your constructive speech:
    1. Claim I (The first point you argue.  Literally say, “Our first claim is that . . . “)
        - Warrant (“This is true because…”)
        - Evidence
        - Impact (“This is important because…”)
    2. Claim II (The second point you argue)
        - Warrant
        - Evidence
        - Impact
    3. Claim III (The third point you argue)
        - Warrant
        - Evidence
        - Impact
5. In cross examination, avoid the trap of over explaining or over questioning. The most memorable points are quick and pithy. If you're asking too long a question, both the other team and the jury will lose track of what you're asking. (You have all other parts of the debate to speech-ify.  This is your time to exract concessions from your opponents directly.)
6. In questions, go on the offensive and ask questions that you know your opponents don’t have good answers for. Good examples of questions include:
    - Testing assumptions: "Does your argument depend on . . . "
    - Highlight tradeoffs: "Does your policy require sacrificing . . . "
    - Clarifications: "What exactly do you mean by . . ."
    - Lock in concessions: "Do you agree that . . . "
7. If you’re over explaining in response, you’re probably losing. More time spent in response is more time spent in your opponents debate frame, and less time in yours. Answer honestly, but remember that too much time in reponse is time that you're not spending pressing your opponent on the weaknesses in their arguments.
6. Remember: The cross examination is more typically won by asking good questions rather than having good responses.  Prepare accordingly.
5. The rebuttal and final focus have different purposes. The *rebuttal* is where you tell the judge and jury why your opponents are wrong and you are right.  The *final focus* is where you focus the judge on jury on why you should win the debate.
5. Use the similar format for your rebuttal and final focus:
    - My opponent's arguments are incorrect becuase/here is why we’ve won today’s round:
        - Reason (Tell the jury very literally why they should vote for you)
        - Reason
        - Reason 
6. Pay attention to your time.  The debate can feel simultaneously short and long - a three minute constructive is plenty of time to say what you need to, so long as you plan well ahead of time.  Use all of your time effectively but do not go over.
7. Speak quickly if you can, but above all else be clear and calm. If you want to perform well you must practice giving your constructive speech at least twice.
8. Use resources from class, including readings and lectures, as well as material from outside class.  Consider the optional readings listed in the course agenda. They are there to help you. 
11. Remember: if you want to win, you need to focus on persuading your judges. How many times have you been in an argument with someone and find yourself thinking, “oh my god why don’t you understand?! The evidence is right there!”?  Facts alone don’t win arguments. *Persuasion* wins arguments. 

## What to prepare

- Typed case papers that are, word for word, what you will read for your constructive.
- Your sources. (Which you will submit).
- Questions for your opponents in the cross-examination. (These can be edited briefly after the first rounds, but you will not have enough time in debate to write good questions without preparing ahead of time.)
- Any notes that will help you prepare for the rejoinder, cross examination, or final focus.  You will not have time to draft a full word for word speech in the debate, so it's good to have some pieces that you can build from.
- A pen and paper so you can take notes on what your opponents say.